name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup Unity
        uses: kuler90/setup-unity@v1
        with:
          unity-version: 2018.4.20f1

      - name: Run a one-line script 1
        run: find /home/runner/Unity/Hub/Editor/2018.4.20f1/Editor/Unity
